### ISSUE TITLE
whatapi.whatapi.RequestException on ORP

### ISSUE THREAD

**Issue by conxr** [nrg101/musicscan#28]
I've been struggling to get this to work on ORP (working just fine on RED) after they changed settings with API requests. 

Traceback (most recent call last):
  File "/Users/*/musicscan-orp/musicscan-cli", line 449, in <module>
    main()
  File "/Users/*/musicscan-orp/musicscan-cli", line 440, in main
    process_release(release, api, music_threshold, processed_dirs, max_search_results)
  File "/Users/*/musicscan-orp/musicscan-cli", line 227, in process_release
    search_matches = search_and_match(api, release, music_threshold,
  File "/Users/*/musicscan-orp/musicscan-cli", line 112, in search_and_match
    torrent_object = api.torrent(group_torrent["torrentId"])
  File "/Users/*/musicscan-orp/musicscan/api.py", line 44, in torrent
    torrent_lookup = self.request(
  File "/usr/local/lib/python3.9/site-packages/whatapi/whatapi.py", line 98, in request
    raise RequestException
whatapi.whatapi.RequestException

Is there a fix or workaround for this? Had a look at editing the file myself but not knowledgeable enough.

**Comment by ilchierc** [comment]
I am having the same issue @nrg101 
This happens when it reaches the same file to scan
